DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(100)                                        NOT NULL,
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         VARCHAR(255)                                        NOT NULL,
    description  VARCHAR(512)                                        NOT NULL,
    is_available boolean                                             NOT NULL,
    owner_id     BIGINT                                              NOT NULL,
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    end_date       TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    item_id        BIGINT                                              NOT NULL,
    booker_id      BIGINT                                              NOT NULL,
    booking_status VARCHAR(100)                                        NOT NULL,
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text      VARCHAR(512),
    item_id   BIGINT                                              NOT NULL,
    author_id BIGINT                                              NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (id)
);

